In [75]:
import numpy as np
import pandas as pd
from scipy import stats
#from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt
import seaborn as sns
sale = pd.read_csv("http://tinyurl.com/ProgStatMtcars")


In [76]:
cyl_vs = pd.crosstab(sale.cyl,sale.vs)
print(cyl_vs.head(100))
O = np.array(cyl_vs)
print(O)

vs    0   1
cyl        
4     1  10
6     3   4
8    14   0
[[ 1 10]
 [ 3  4]
 [14  0]]


In [77]:
#1
E = np.zeros(O.shape)
for i in range(O.shape[0]):
    for j in range(O.shape[1]):
        E[i,j]=O[i].sum()*O[:,j].sum()/O.sum()
        #print(O[i],O[:,j])
chi2_cal,p_val,dof,E =stats.chi2_contingency(O,correction=False)
print(chi2_cal,p_val,dof,E)

v=(3-1)*(2-1)
print(v)
chi2_crit = stats.chi2.isf(0.05,2)
print(chi2_crit)

21.339929911358485 2.3232347637946903e-05 2 [[6.1875 4.8125]
 [3.9375 3.0625]
 [7.875  6.125 ]]
2
5.991464547107983


In [83]:
#2
print(cyl_vs.head(100))
x = np.array(cyl_vs)
#print(x)
#print(n)
O = np.array([sum(i) for i in x])
print(O)
n = sum(O)
print(n)
p = np.array([2/5,1/5,2/5])
E = np.round(n*p)
print(E)




vs    0   1
cyl        
4     1  10
6     3   4
8    14   0
[11  7 14]
32
[13.  6. 13.]


In [86]:
chi2_cal,p_val =stats.chisquare(f_obs=O,f_exp=E)
print(chi2_cal,p_val)
v= 3-1
chi2_crit = stats.chi2.isf(0.1,v)
print(chi2_crit)

0.5512820512820513 0.7590853740437935
4.605170185988092


In [99]:
#3
#print(sale.hp.head(100))
r,p_val = stats.pearsonr(x=sale.hp,y=sale.mpg)
print(r,p_val)

Sr = np.sqrt((1-r**2)/(31-2))
t_cal =  r/(Sr)
print(t_cal)
t_crit_right = stats.t.isf(0.05/2,df= 31-2)
print(t_crit_right)
t_crit_left = -t_crit_right

-0.7761683718265864 1.7878352541210675e-07
-6.629063017158836
2.0452296421327034
